### ISSUE TITLE
Bob Greenhouse compatibility

### ISSUE THREAD

**Issue by YPetremann** [joshinils/island_spawn#3]
In order to make this game playable with Bob Greenhouse, you should simply add it as a optionnal dependency, it fix trees not being placable.

Also you should make sure that every prototypes follow the factorio standards that makes the mod working with all mods, in this case items needs an "order" key in their prototype.

**Comment by joshinils** [comment]
ok, though bob has its own recipe for seedlings which also show up when the research is completed. can i remove that?

also the order strings i added are empty. maybe that is a bad thing, but it doesnt bug out, so yeah.
